app = "av-main-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile.main"

[processes]
  app = "python main_env/main_bot.py"

[machines]
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
